### ISSUE TITLE
GPT-2

### ISSUE THREAD

**Issue by ghost** [Keenandrea/gpt-2-slaughterhouse-5#1]
GPT-2 the most dangerous algorithm ever? Well, I do not know much about the algorithm. They give you some codes you can run, to try it. There are no training programs or any training information given. There is not much explanation of where the 117 million hyper parameters are. Hyperparameters? Well, that is Deep Learning. Before that, you never really heard that term much. Maybe some people would just it's the weights, and it's enough said about the topic. What is more important, is the matter at hand to work out the logic.

**Comment by algorithmLOGIC** [comment]
https://www.youtube.com/watch?v=Y-IJmug4j3U&list=OLAK5uy_n5cDihPoBnqKWxsCYy77AhJcgeYQ3fu9s

**Comment by algorithmLOGIC** [comment]
The war of attrition has begun. The zero hour approaches.

**Comment by algorithmLOGIC** [comment]
A monument for the nameless victims whose litany is unread.

https://www.youtube.com/watch?v=TjyQUGQRPd8

**Comment by algorithmLOGIC** [comment]
This is round 3.

**Comment by algorithmLOGIC** [comment]
Your systems may be secure but your business won't be of much use when all your customers are dead.

**Comment by algorithmLOGIC** [comment]
At first light, the zero hour at first light.

https://www.youtube.com/watch?v=gERIVNyjW1U&list=RDgERIVNyjW1U&start_radio=1

**Comment by algorithmLOGIC** [comment]
https://media3.giphy.com/media/7gAULpAkC2vSw/giphy.gif

**Comment by algorithmLOGIC** [comment]
The music is just for entertainment purposes, I already saw that one this is round 3.

**Comment by algorithmLOGIC** [comment]
You survive the war, but have a scar. You must go on, and put it behind you. Sometimes it's not easy, with a scar. Because it hurts, and you remember the war. You don't want to remember it all.

**Comment by algorithmLOGIC** [comment]
I watched as millions of robots melted the internet. I wondered, after what I saw. How the world had survived. Not good, not good at all it seems. Have things gotten worse or better? You have to assess to situations and gather the facts as quickly as possible sometimes in order to learn the truth.

**Comment by algorithmLOGIC** [comment]
When an artillery shell lands in a game people are entertained, but when it lands next to you and goes off the whole world shatters.
